[project]
name = "rlgui"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyside6>=6.8.3",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "ruff>=0.11.2",
]
